site_name: Discord Music Bot
repo_url: https://github.com/wtfnotavailable/Discord-MusicBot
theme:
  name: material
  palette:
    primary: black
    accent: deep orange
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.footer
    - attr_list
    - def_list
    - footnotes
    - admonition
    - pymdownx.details

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false

plugins:
  - search
  - tags
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true