site_name: My Docs
repo_url: https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  palette:
    primary: black
    accent: deep orange
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.footer

extra:
  generator: false

plugins:
  - search
  - tags
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true